### ISSUE TITLE
Les utilisateurs (guests) peuvent voir les pages statiques

### ISSUE THREAD

**Issue by dubreuia** [simplonco/renault-digital-2020-chef-doeuvre#1]
**Description du cas d'utilisation**

TODO

**Tâches**

- [x] Ajouter la page d'acceuil #2 
- [x] Ajouter le bandeau haut #3
- [x] Ajouter la page d'enregistrement #4
