### ISSUE TITLE
Les utilisateurs (authentifiés) peuvent créer, voir, modifier et supprimer des synthétiseurs

### ISSUE THREAD

**Issue by dubreuia** [simplonco/renault-digital-2020-chef-doeuvre#5]
**Description du cas d'utilisation**

TODO

**Tâches**

- [x] Ajouter la page de visualisation de synth #6 
- [x] Ajouter la page de création de synth #7 
- [ ] Ajouter le bouton de modification de l'image de synth
- [ ] Ajouter le bouton de suppression de synth #8 

...
